# docker-compose.yml
services:
  claude-api-v3:
    container_name: claude_v3
    build: .
    ports:
      - "8001:8001"
    restart: unless-stopped
    mem_limit: 1g
    volumes:
      - ./pdfs:/app/pdfs
      - ./resultados:/app/resultados
      - ./claude_cookies_selenium.json:/app/claude_cookies_selenium.json